site_name: desklab Arduino Bibliothek

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - navigation.indexes

extra_css:
  - stylesheets/style.css

nav:
- Erste Schritte: 
  - index.md
  - Installation: start/installation.md
- Photometer: 
  - photometer/index.md
  - Aufbau der Schaltung: photometer/aufbau-schaltung.md
  - Programmcode: photometer/programmcode.md
- Datenübertragung: 
  - datenuebertragung/index.md
  - Senden: datenuebertragung/senden.md
  - Empfangen: datenuebertragung/empfangen.md
  - API: datenuebertragung/api.md
- Development:
  - development/index.md
  - Changelog: development/changelog.md
  - Release: development/release.md

extra:
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:post@desk-lab.de
    - icon: fontawesome/brands/github
      link: https://github.com/desklab

repo_url: https://github.com/desklab/desklab-arduino-lib
repo_name: desklab/desklab-arduino-lib
edit_uri: ""

copyright: Copyright &copy; 2018 - 2022 desklab gUG (haftungsbeschränkt)